name: Issue (testing, DO NOT USE)
description: for reporting any issue
title: "[Issue] "
labels: ["ISSUE"]
body:
  - type: checkboxes
    attributes:
      label: Before you submit
      options:
        - label: I have read the [Troubleshooting](https://end-4.github.io/dots-hyprland-wiki/en/i-i/04troubleshooting/) and [Usage](https://end-4.github.io/dots-hyprland-wiki/en/i-i/02usage/) pages.
          required: true
        - label: I've updated to the latest version following the [guidance](https://end-4.github.io/dots-hyprland-wiki/en/i-i/01setup/#updating).
          required: false # Not required cuz user may have failed to do so
        - label: I've had the system packages up to date.
          required: false # Not required cuz user may have failed to do so

  - type: input
    attributes:
      label: "Linux distro:"
      description: Not sure? Run `lsb_release -a` or `cat /etc/{lsb,os}-release`.
      placeholder: e.g. Arch Linux
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        Describe your problem below.
        1. Use `LANG=C LC_ALL=C` to get the output of a command in English, eg. `LANG=C LC_ALL=C date` displays time in English.
        2. If it throws errors, **PLEASE**, attach logs and describe in detail if possible.
           - Bar and widgets not showing? run `pkill ags; ags` for logs.
           - Installation failed? Run installation again for logs.
           - Optionally also run `./diagnose` inside the repo for logs.

  - type: textarea
    attributes:
      label: The issue
      value: |
        #blank
        (Describe your issue here!)
        #blank
        <!-- ↓↓ DO NOT IGNORE THIS. NO HELP CAN BE GIVEN WITHOUT SUFFICIENT LOGS -->
        <details><summary>Logs</summary>
        #blank
        ```
        (Put your log content here!)
        ```
        #blank
        </details>
    validations:
      required: true
